" starts vim with the server enabled
" :help vimtex-clientserver
if empty(v:servername) && exists('*remote_startserver')
  call remote_startserver('VIM')
endif

let g:vimtex_syntax_custom_cmds = [
            \ {'name': 'rI', 'mathmode': 1, 'concealchar': 'I'},
            \ {'name': 'rF', 'mathmode': 1, 'concealchar': 'F'},
            \ {'name': 'rK', 'mathmode': 1, 'concealchar': 'K'},
            \ {'name': 'rT', 'mathmode': 1, 'concealchar': 'T'},
            \ {'name': 'rc', 'mathmode': 1, 'concealchar': 'c'},
            \ {'name': 'rd', 'mathmode': 1, 'concealchar': 'd'},
            \ {'name': 'rg', 'mathmode': 1, 'concealchar': 'g'},
            \ {'name': 'rr', 'mathmode': 1, 'concealchar': 'r'},
            \ {'name': 'rt', 'mathmode': 1, 'concealchar': 't'},
            \ {'name': 'rx', 'mathmode': 1, 'concealchar': 'x'},
            \ {'name': 'rz', 'mathmode': 1, 'concealchar': 'z'},
            \ {'name': 'bB', 'mathmode': 1, 'concealchar': '𝔹'},
            \ {'name': 'bC', 'mathmode': 1, 'concealchar': 'ℂ'},
            \ {'name': 'E', 'mathmode': 1, 'concealchar': '𝔼'},  
            \ {'name': 'bE', 'mathmode': 1, 'concealchar': '𝔼'},
            \ {'name': 'bF', 'mathmode': 1, 'concealchar': '𝔽'},
            \ {'name': 'bG', 'mathmode': 1, 'concealchar': '𝔾'},
            \ {'name': 'bH', 'mathmode': 1, 'concealchar': 'ℍ'},
            \ {'name': 'bI', 'mathmode': 1, 'concealchar': '𝕀'},
            \ {'name': 'bM', 'mathmode': 1, 'concealchar': '𝕄'},
            \ {'name': 'bN', 'mathmode': 1, 'concealchar': 'ℕ'},
            \ {'name': 'bP', 'mathmode': 1, 'concealchar': 'ℙ'},
            \ {'name': 'bO', 'mathmode': 1, 'concealchar': '𝕆'},
            \ {'name': 'bQ', 'mathmode': 1, 'concealchar': 'ℚ'},
            \ {'name': 'bR', 'mathmode': v:true, 'hlgroup': 'math', 'concealchar': 'ℝ'}, 
            \ {'name': 'bS', 'mathmode': 1, 'concealchar': '𝕊'},
            \{'name': 'bV', 'mathmode': 1, 'concealchar': '𝕍'},  
            \ {'name': 'bZ', 'mathmode': 1, 'concealchar': 'ℤ'},
            \ {'name': 'mbA', 'mathmode': 1, 'concealchar': '𝐀'},
            \ {'name': 'mbB', 'mathmode': 1, 'concealchar': '𝐁'},
            \ {'name': 'mbC', 'mathmode': 1, 'concealchar': '𝐂'},
            \ {'name': 'mbD', 'mathmode': 1, 'concealchar': '𝐃'},
            \ {'name': 'mbI', 'mathmode': 1, 'concealchar': '𝐈'},
            \ {'name': 'mbJ', 'mathmode': 1, 'concealchar': '𝐉'},
            \ {'name': 'mbK', 'mathmode': 1, 'concealchar': '𝐊'},
            \ {'name': 'mbM', 'mathmode': 1, 'concealchar': '𝐌'},
            \ {'name': 'mbP', 'mathmode': 1, 'concealchar': '𝐏'},
            \ {'name': 'mbR', 'mathmode': 1, 'concealchar': '𝐑'},
            \ {'name': 'mbU', 'mathmode': 1, 'concealchar': '𝐔'},
            \ {'name': 'mbV', 'mathmode': 1, 'concealchar': '𝐕'},
            \ {'name': 'mbW', 'mathmode': 1, 'concealchar': '𝐖'},
            \ {'name': 'mbX', 'mathmode': 1, 'concealchar': '𝐗'},
            \ {'name': 'mbY', 'mathmode': 1, 'concealchar': '𝐘'},
            \ {'name': 'mbb', 'mathmode': 1, 'concealchar': '𝐛'},
            \ {'name': 'mbc', 'mathmode': 1, 'concealchar': '𝐜'},
            \ {'name': 'mbd', 'mathmode': 1, 'concealchar': '𝐝'},
            \ {'name': 'mbe', 'mathmode': 1, 'concealchar': '𝐞'},
            \ {'name': 'mbf', 'mathmode': 1, 'concealchar': '𝐟'},
            \ {'name': 'mbg', 'mathmode': 1, 'concealchar': '𝐠'},
            \ {'name': 'mbl', 'mathmode': 1, 'concealchar': '𝐥'},
            \ {'name': 'mbm', 'mathmode': 1, 'concealchar': '𝐦'},
            \ {'name': 'mbn', 'mathmode': 1, 'concealchar': '𝐧'},
            \ {'name': 'mbp', 'mathmode': 1, 'concealchar': '𝐩'},
            \ {'name': 'mbq', 'mathmode': 1, 'concealchar': '𝐪'},
            \ {'name': 'mbs', 'mathmode': 1, 'concealchar': '𝐬'},
            \ {'name': 'mbt', 'mathmode': 1, 'concealchar': '𝐭'},
            \ {'name': 'mbu', 'mathmode': 1, 'concealchar': '𝐮'},
            \ {'name': 'mbv', 'mathmode': 1, 'concealchar': '𝐯'},
            \ {'name': 'mbw', 'mathmode': 1, 'concealchar': '𝐰'},
            \ {'name': 'mbx', 'mathmode': 1, 'concealchar': '𝐱'},
            \ {'name': 'mby', 'mathmode': 1, 'concealchar': '𝐲'},
            \ {'name': 'mbz', 'mathmode': 1, 'concealchar': '𝐳'},
            \ {'name': 'bsigma', 'mathmode': 1, 'concealchar': 'σ', 'argstyle': 'bold'},
            \ {'name': 'btheta', 'mathmode': 1, 'concealchar': 'θ', 'argstyle': 'bold'},
            \ {'name': 'cA', 'mathmode': 1, 'concealchar': '𝒜'},
            \ {'name': 'cB', 'mathmode': 1, 'concealchar': 'ℬ'},
            \ {'name': 'cC', 'mathmode': 1, 'concealchar': '𝒞'},
            \ {'name': 'cD', 'mathmode': 1, 'concealchar': '𝒟'},
            \ {'name': 'cE', 'mathmode': 1, 'concealchar': 'ℰ'},
            \ {'name': 'cF', 'mathmode': 1, 'concealchar': 'ℱ'},
            \ {'name': 'cG', 'mathmode': 1, 'concealchar': '𝒢'},
            \ {'name': 'cH', 'mathmode': 1, 'concealchar': 'ℋ'},
            \ {'name': 'cI', 'mathmode': 1, 'concealchar': 'ℐ'},
            \ {'name': 'cJ', 'mathmode': 1, 'concealchar': '𝒥'},
            \ {'name': 'cK', 'mathmode': 1, 'concealchar': '𝒦'},
            \ {'name': 'cL', 'mathmode': 1, 'concealchar': 'ℒ'},
            \ {'name': 'cM', 'mathmode': 1, 'concealchar': 'ℳ'},
            \ {'name': 'cN', 'mathmode': 1, 'concealchar': '𝒩'},
            \ {'name': 'cO', 'mathmode': 1, 'concealchar': '𝒪'},
            \ {'name': 'cP', 'mathmode': 1, 'concealchar': '𝒫'},
            \ {'name': 'cQ', 'mathmode': 1, 'concealchar': '𝒬'},
            \ {'name': 'cR', 'mathmode': 1, 'concealchar': 'ℛ'},
            \ {'name': 'cS', 'mathmode': 1, 'concealchar': '𝒮'},
            \ {'name': 'cT', 'mathmode': 1, 'concealchar': '𝒯'},
            \ {'name': 'cU', 'mathmode': 1, 'concealchar': '𝒰'},
            \ {'name': 'cV', 'mathmode': 1, 'concealchar': '𝒱'},
            \ {'name': 'cW', 'mathmode': 1, 'concealchar': '𝒲'},
            \ {'name': 'cX', 'mathmode': 1, 'concealchar': '𝒳'},
            \ {'name': 'cY', 'mathmode': 1, 'concealchar': '𝒴'},
            \ {'name': 'cZ', 'mathmode': 1, 'concealchar': '𝒵'},
            \ {'name': 'bmX', 'mathmode': 1, 'argsstyle': 'bold', 'concealchar': 'X'},
            \ {'name': 'bmb', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'b'},
            \ {'name': 'bmc', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'c'},
            \ {'name': 'bmd', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'd'},
            \ {'name': 'bme', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'e'},
            \ {'name': 'bmg', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'g'},
            \ {'name': 'bml', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'l'},
            \ {'name': 'bmm', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'm'},
            \ {'name': 'bmn', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'n'},
            \ {'name': 'bmp', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'p'},
            \ {'name': 'bmq', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'q'},
            \ {'name': 'bms', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 's'},
            \ {'name': 'bmt', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 't'},
            \ {'name': 'bmu', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'u'},
            \ {'name': 'bmv', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'v'},
            \ {'name': 'bmw', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'w'},
            \ {'name': 'bmx', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'x'},
            \ {'name': 'bmy', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'y'},
            \ {'name': 'bmz', 'mathmode': 1, 'argstyle': 'bold', 'concealchar': 'z'},
            \ {'name': 'kx', 'mathmode': 1, 'concealchar': '𝔵'},
            \ {'name': 'kA', 'mathmode': 1, 'concealchar': '𝔄'},
            \ {'name': 'kB', 'mathmode': 1, 'concealchar': '𝔅'},
            \ {'name': 'kD', 'mathmode': 1, 'concealchar': '𝔇'},
            \ {'name': 'kF', 'mathmode': 1, 'concealchar': '𝔉'},
            \ {'name': 'kG', 'mathmode': 1, 'concealchar': '𝔊'},
            \ {'name': 'kH', 'mathmode': 1, 'concealchar': 'ℌ'},
            \ {'name': 'kI', 'mathmode': 1, 'concealchar': 'ℑ'},
            \ {'name': 'kK', 'mathmode': 1, 'concealchar': '𝔎'},
            \ {'name': 'kL', 'mathmode': 1, 'concealchar': '𝔏'},
            \ {'name': 'kM', 'mathmode': 1, 'concealchar': '𝔐'},
            \ {'name': 'kR', 'mathmode': 1, 'concealchar': 'ℜ'},
            \ {'name': 'kS', 'mathmode': 1, 'concealchar': '𝔖'},
            \ {'name': 'kX', 'mathmode': 1, 'concealchar': '𝔛'},
            \ {'name': 'sA', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'A'},
            \ {'name': 'sB', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'B'},
            \ {'name': 'sC', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'C'},
            \ {'name': 'sL', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'L'},
            \ {'name': 'sM', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'M'},
            \ {'name': 'sN', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'N'},
            \ {'name': 'sP', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'P'},
            \ {'name': 'sS', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'S'},
            \ {'name': 'sU', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'U'},
            \ {'name': 'sX', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'X'},
            \ {'name': 'sY', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'Y'},
            \ {'name': 'sZ', 'mathmode': 1, 'argstyle': 'boldital', 'concealchar': 'Z'},
            \ {'name': 'defeq', 'mathmode': 1, 'concealchar': '≔'},
            \ {'name': 'eqdef', 'mathmode': 1, 'concealchar': '≕'},
            \ {'name': 'dif', 'mathmode': 1, 'concealchar': 'd'},
            \ ]


let g:vimtex_syntax_custom_cmds_with_concealed_delims = [
          \ {'name': 'set',
          \  'mathmode': 1,
          \  'cchar_open': '{',
          \  'cchar_close': '}'},
          \ {'name': 'abs',
          \  'mathmode': 1,
          \  'cchar_open': '|',
          \  'cchar_close': '|'},
          \ {'name': 'norm',
          \ 'mathmode': 1,
          \ 'cchar_open': '‖',
          \ 'cchar_close': '‖'},
          \ {'name': 'ang',
          \ 'mathmode': 1,
          \ 'cchar_open': '<',
          \ 'cchar_close': '>'},
          \]
